version: '2'
plugins:
  editorconfig:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: 'eslint-7'
    config:
    extensions:
      - .js
      - .jsx
      - .ts
      - .tsx
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
  markdownlint:
    enabled: true
exclude_patterns:
  - '.husky/'
  - '.storybook/'
  - '.vscode/'
  - 'example/'
  - 'jest/'
  - 'node_modules/'
  - 'src/types/'
  - '.eslintrc'
  - '.prettierrc'
  - '.commitlint.config.js'
  - 'rollup.config.js'
  - 'tailwind.config.js'
  - 'yarn.lock'
